### ISSUE TITLE
Timetable for a new release?

### ISSUE THREAD

**Issue by kalylian** [nanoporetech/rerio#21]
Hi,

I noticed that the latest release (version 3.5.1) is almost a year old. Is there a timetable for the next release?

Kind regards,

Gudrun

**Comment by tmassingham-ont** [comment]
Rerio is versioned according to minimum version of Guppy required to run all of the models in the repository. New models are continuously being added but the release version number will only change if they require a more recent version of Guppy is required.  We should have bumped the version when the latest transducer "CRF" models were added since they require Guppy 4.4 -- I'll get this done!

**Comment by kalylian** [comment]
Thanks a lot! :)
