### ISSUE TITLE
miscalled CpG at repeat sequence

### ISSUE THREAD

**Issue by TerrenceT-79** [nanoporetech/rerio#38]
@marcus1487 I have some repeat sequence that I would like to get methylation calls over. The repeats are GGCCGG the internal CpG in this sequence actually miscalls at one of the CpG positions nearly every time in both the fw and rev strands. I am able to get some methylation calls where the correct basecalls are made but the incorrect T and A calls make it difficult to interpret the data. this is with the res_dna_r941_min_modbases_5mC_CpG_v001.cfg model.
thanks

<img width="1424" alt="Screen Shot 2022-04-14 at 11 54 20 PM" src="https://user-images.githubusercontent.com/25189612/163515674-ccad43b1-8d97-483f-9eed-8ed6e347e2ac.png">
.

_Originally posted by @TerrenceT-79 in https://github.com/nanoporetech/rerio/issues/31#issuecomment-1099829169_

**Comment by marcus1487** [comment]
I would highly recommend switching to the newer Remora modified basecalling models which use standard basecalling models and call modified bases on top of the canonical basecaller. These Remora models can be used from both megalodon and bonito (and are integrated into Guppy).

The issue here is one of the reasons this switch was made. Performing canonical and modified base calling at the same time is quite a bit more complicated.
