### ISSUE TITLE
rerio modbases-all-contexts model for R10.4.1

### ISSUE THREAD

**Issue by Kevin-Brockers** [nanoporetech/rerio#47]
Dear all,

I am interested in m6A and mC methylations in direct DNA sequencing samples using a MinIon

We are considering to use the R10.4.1 flow cell chemistry but I cannot find a suitable model, similar to the `res_dna_r941_min_modbases-all-context_v001` model for the older flow cell chemistry.

Is there something planned and or even a release schedule?

All best,
Kevin

**Comment by AlexdeMendoza** [comment]
Dear all, 

I see there has been quite a lot of people asking for the same, but now I am about to buy new flow cells, and I would like to know if there is any plan to release this model for R10.4.1 instead of having to buy the older R9.4.1. Any update on this end?

I am also assuming there are no plans to get these to work in the PromethION? 

Thanks, 

Alex

**Comment by marcus1487** [comment]
This is the top priority and we are actively working towards a release of the 5mC and 6mA all-context models for kit14 (R10.4.1 E8.2). These models will be applicable to both minion and promethion data when released. While we are working hard on this problem, this is still a research target, so there is no specific release schedule set at this time.

**Comment by mp15** [comment]
I notice there are 400bps all context models for 4kHz data available now, any plans for 260bps? I have a few remaining cells I would like to recall.

**Comment by marcus1487** [comment]
There are no plans to add all-context models to the 260bps condition at this time.
