### ISSUE TITLE
[ERROR] Model path not found

### ISSUE THREAD

**Issue by Wshengquan** [nanoporetech/rerio#65]
Hi，
I have used Rerio to download the models for R10.4.1 data when I want to call variants by Clair3 and I run :
run_clair3.sh
--bam_fn=../LR1D.sort.bam
--ref_fn=/share/home/yzwl_hanxs/basecalling/referenceGene/Sus_scrofa.Sscrofa11.1.dna_sm.toplevel.fa
--threads=4 --platform='ont'
--model_path='/share/home/yzwl_hanxs/app/rerio/clair3_models/r1041_e82_400bps_sup_g615_model'
--output=/share/home/yzwl_hanxs/company-third/LR1D/bam/SNP
And then the error was reported：
[INFO] CLAIR3 VERSION: v1.0.8
[INFO] BAM FILE PATH: /share/home/yzwl_hanxs/company-third/LR1D/bam/SNP/../LR1D.sort.bam
[INFO] REFERENCE FILE PATH: /share/home/yzwl_hanxs/basecalling/referenceGene/Sus_scrofa.Sscrofa11.1.dna_sm.toplevel.fa
[INFO] MODEL PATH: /share/home/yzwl_hanxs/app/rerio/clair3_models/r1041_e82_400bps_sup_g615_model
[INFO] OUTPUT FOLDER: /share/home/yzwl_hanxs/company-third/LR1D/bam/SNP
[INFO] PLATFORM: ont
[INFO] THREADS: 4
[INFO] BED FILE PATH: EMPTY
[INFO] VCF FILE PATH: EMPTY
[INFO] CONTIGS: EMPTY
[INFO] CONDA PREFIX: /share/home/yzwl_hanxs/anaconda3/envs/clair3
[INFO] SAMTOOLS PATH: samtools
[INFO] PYTHON PATH: python3
[INFO] PYPY PATH: pypy3
[INFO] PARALLEL PATH: parallel
[INFO] WHATSHAP PATH: whatshap
[INFO] LONGPHASE PATH: EMPTY
[INFO] CHUNK SIZE: 5000000
[INFO] FULL ALIGN PROPORTION: 0.7
[INFO] FULL ALIGN REFERENCE PROPORTION: 0.1
[INFO] PHASING PROPORTION: 0.7
[INFO] MINIMUM MQ: 5
[INFO] MINIMUM COVERAGE: 2
[INFO] SNP AF THRESHOLD: 0.08
[INFO] INDEL AF THRESHOLD: 0.15
[INFO] BASE ERROR IN GVCF: 0.001
[INFO] GQ BIN SIZE IN GVCF: 5
[INFO] ENABLE FILEUP ONLY CALLING: False
[INFO] ENABLE FAST MODE CALLING: False
[INFO] ENABLE CALLING SNP CANDIDATES ONLY: False
[INFO] ENABLE PRINTING REFERENCE CALLS: False
[INFO] ENABLE OUTPUT GVCF: False
[INFO] ENABLE HAPLOID PRECISE MODE: False
[INFO] ENABLE HAPLOID SENSITIVE MODE: False
[INFO] ENABLE INCLUDE ALL CTGS CALLING: False
[INFO] ENABLE NO PHASING FOR FULL ALIGNMENT: False
[INFO] ENABLE REMOVING INTERMEDIATE FILES: False
[INFO] ENABLE LONGPHASE FOR INTERMEDIATE VCF PHASING: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING WHATSHAP: False
[INFO] ENABLE PHASING FINAL VCF OUTPUT USING LONGPHASE: False
[INFO] ENABLE HAPLOTAGGING FINAL BAM: False
[INFO] ENABLE LONG INDEL CALLING: False
[INFO] ENABLE C_IMPLEMENT: True

ESC[31m[ERROR] Model path not foundESC[0m

and then I checked this :
![1720268229006](https://github.com/nanoporetech/rerio/assets/145557567/3926485a-bbb0-4637-a5a2-a850da16c48d)

Why does this happen
Any help to overcome this is appreciated!

Best

**Comment by davidnewman02** [comment]
The error from Clair3 looks like the model can not be found and/or hasn't been downloaded correctly. 

It looks like you are trying to use the `r1041_e82_400bps_sup_g615_model`. Is this the model you intended to use? Did this model download correctly? What is the content of the folder: `/share/home/yzwl_hanxs/app/rerio/clair3_models/r1041_e82_400bps_sup_g615_model` ? 

From your screenshot it seems like the only clair3 models you have downloaded are the `v430` and `v500` (highlighted in green)? Depending on what model you have used in basecalling these are the models we would recommend rather than the outdated `g615` model.

If you are still having trouble, could you please include the commands used to download the model from Rerio.

**Comment by Wshengquan** [comment]
Thank you very much for your reply. It should be caused by the incomplete download of my model. I have solved it. Thanks again for your reply
